[package]
name = "oog"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-files = "0.1"
actix-web = "1.0"
chrono = "0.4"
chrono-english = "0.1"
dotenv = "0.15"
env_logger = "0.7"
json = "0.12"
lazy_static = "1.4"
log = "0.4"
notify = "4.0"
regex = "1.0"
reqwest = "0.9"
scraper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "1.0"
